### ISSUE TITLE
selected frame mode isn't recognised

### ISSUE THREAD

**Issue by Tonacatecuhtli** [Strunzdesign/snet-gateway#1]
You connect a TCP-Client to the snet-gateway.
You want to use the GATEWAY_ACCESS_FRAME_LENGTH communication protocol.
To subscribe to all s-net services you have to send the following message:
`0x00,`
`0x00,`
`0x40,//SrcSSA Byte 1`
`0x01,//SrcSSA Byte 2`
`0x40,//DstcSSA Byte 1`
`0x00,//DstcSSA Byte 2`
`0x00, //ARQ = 0`
`0x00, //SrcSrv = 00`
`0xb0, //DstSrv = b0 = pub/sub service`
`0x00,`
`0x10,`
`0xff// 1 Byte payload = subscribe all services`

that are 12 bytes payload so the Header for the GATEWAY_ACCESS_FRAME_LENGTH protocol has to be 
`0x80,//select the GATEWAY_ACCESS_FRAME_LENGTH protocol`
`0x0c//Payload length = 12 Byte`

The resulting message send over the TCP-Socket is:
`send: 80 0c 00 00 40 01 40 00 00 00 b0 00 10 ff`

The [documentation](https://github.com/Strunzdesign/snet-gateway/blob/master/doc/protocol.md) is stating that "This frame format is the same for frames sent to and received from the gateway" that implies you should receive messages in the GATEWAY_ACCESS_FRAME_LENGTH protocol format.
But you receive messages in the GATEWAY_ACCESS_FRAME_ESCAPED protocol farmat.
`receive: 7e 00 00 40 00 40 01 00 b0 b0 00 11 ff 00 7e`
`receive: 7e 00 10 00 01 40 00 80 00 09 09 00 1a 00 00 05 c6 00 00 01 1a 01 a0 7e`

**Comment by Strunzdesign** [comment]
Bingo! You found a bug :-)

Thanks for your report, I just committed the respective fix. After you tested this, I'm going to create a new release. The length-based framing mode, which is the recommended mode for all future gateway clients, was just not tested enough due to the lack of a first gateway client. You wrote it, so you triggered this issue.

Regards,
Florian
